"""Initial Migration

Revision ID: 9f830b8a6ee6
Revises: 
Create Date: 2020-12-06 14:57:58.791938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f830b8a6ee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    op.create_foreign_key(None, 'downvotes', 'blogs', ['blog_id'], ['id'])
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'upvotes', 'blogs', ['blog_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.alter_column('blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
